"""Deterministic classification: points -> ACMG class (plan Step 0.2, §A.1).

The classification is computed *deterministically* from the points ledger; it is
never generated by a language model (a core safety property of the system).

Tavtigian 2020 naturally-scaled bands:
    P   : C >= 10
    LP  : 6 <= C <= 9
    VUS : 0 <= C <= 5
    LB  : -6 <= C <= -1
    B   : C <= -7
BA1 is a standalone benign pre-filter (excluded from the Bayesian sum, per ClinGen).
"""
from __future__ import annotations

from typing import Protocol

from core.schemas import Classification, PointsLedger

# Ordered high -> low; the first threshold the points meet wins.
BANDS: list[tuple[float, Classification]] = [
    (10, Classification.P),
    (6, Classification.LP),
    (0, Classification.VUS),
    (-6, Classification.LB),
]  # else Benign


class VCEPSpec(Protocol):
    """Minimal interface the point engine needs from a gene spec.

    Full loader lives in ``rules/vcep_loader.py`` (Step 0.2). The protocol keeps
    the engine swappable and unit-testable without a real CSpec file.
    """

    version: str

    def ba1_met(self, ledger: PointsLedger) -> bool: ...


def classify(ledger: PointsLedger, spec: VCEPSpec | None = None) -> Classification:
    """Return the ACMG classification for a ledger under an optional gene spec."""
    if spec is not None and spec.ba1_met(ledger):
        return Classification.B
    pts = ledger.points
    for threshold, cls in BANDS:
        if pts >= threshold:
            return cls
    return Classification.B
